apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/part-of: konsti
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app.kubernetes.io/part-of: konsti
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mongodb
