apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/part-of: konsti
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mongodb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: konsti
      app.kubernetes.io/component: database
      app.kubernetes.io/name: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: konsti
        app.kubernetes.io/component: database
        app.kubernetes.io/name: mongodb
    spec:
      enableServiceLinks: false
      containers:
        - name: mongodb
          image: !Var mongodb_image
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
