defaultSemverRangePrefix: ""

enableConstraintsChecks: true

enableScripts: false

nodeLinker: node-modules

logFilters:
  - text: "eslint is listed by your project with version 10.2.0 (pd85124), which doesn't satisfy what eslint-plugin-jsx-a11y and other dependencies request (but they have non-overlapping ranges!)."
    level: discard
  - text: "@sentry/node is listed by your project with version 10.47.0 (p94b0d0), which doesn't satisfy what winston-transport-sentry-node requests (^8.13.0)."
    level: discard
  - text: "client@workspace:client doesn't provide rollup (p03be1e), requested by @mdx-js/rollup."
    level: discard

npmMinimalAgeGate: 10080

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.13.0.cjs
