defaultSemverRangePrefix: ""

enableConstraintsChecks: true

nodeLinker: node-modules

packageExtensions:
  ts-node-dev@*:
    peerDependencies:
      "@types/node": "*" # Workaround for https://github.com/wclr/ts-node-dev/issues/319

yarnPath: .yarn/releases/yarn-4.0.2.cjs
