defaultSemverRangePrefix: ""

enableConstraintsChecks: true

enableScripts: false

logFilters:
  - code: YN0088
    level: discard
  - level: discard
    pattern: "eslint is listed by your project with version *, which doesn't satisfy what eslint-plugin-jsx-a11y and other dependencies request *"
  - level: discard
    pattern: "@sentry/node is listed by your project with version *, which doesn't satisfy what winston-transport-sentry-node requests *"
  - level: discard
    pattern: "client@workspace:client doesn't provide rollup *, requested by @mdx-js/rollup."

nodeLinker: node-modules

npmMinimalAgeGate: 10080

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
