version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - CONN_STRING=mongodb://mongo:27017
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    # ME_CONFIG_MONGODB_ADMINUSERNAME: root
    # ME_CONFIG_MONGODB_ADMINPASSWORD: example

  cypress:
    image: 'cypress/included:6.2.1'
    depends_on:
      - server
    environment:
      - CYPRESS_baseUrl=http://server:5000
    working_dir: /client
    volumes:
      - ./client:/client
    entrypoint: /bin/sh -c "sleep 10 && cypress run --browser chrome --headless --config-file false --project ./build"
