version: "3.8"

services:
  playwright:
    network_mode: host
    build:
      context: ../client/playwright
      dockerfile: Dockerfile
    environment:
      - PLAYWRIGHT_BASEURL=http://localhost:5000
    depends_on:
      - server
    volumes:
      - ../client/playwright/test-results:/playwright/test-results # In relation to root level docker-compose.yml file
    entrypoint: /bin/sh -c "/usr/local/bin/waitforit -address=localhost:5000 -timeout=60 && npx playwright test"
