version: '3.8'

services:
  cypress:
    image: 'cypress/included:7.3.0'
    environment:
      - CYPRESS_baseUrl=http://server:5000
      - CYPRESS_PROJECT_ID=btftv2
      - CYPRESS_RECORD_KEY=${CYPRESS_DASHBOARD_RECORD_KEY}
    working_dir: /client
    volumes:
      - ./client:/client # In relation to root level docker-compose.yml file
    depends_on:
      - server
    entrypoint: /bin/sh -c "
        wget -q -O /usr/local/bin/waitforit https://github.com/maxcnunes/waitforit/releases/download/v2.4.1/waitforit-linux_amd64
        && chmod +x /usr/local/bin/waitforit
        && /usr/local/bin/waitforit -address=server:5000 -timeout=60
        && cypress run --browser chrome --headless --config-file false --project ./build --record
      "
