version: '3.8'

services:
  cypress:
    image: 'cypress/included:6.2.1'
    environment:
      - CYPRESS_baseUrl=http://server:5000
    working_dir: /client
    volumes:
      - ./client:/client
    entrypoint: /bin/sh -c "sleep 10 && cypress run --browser chrome --headless --config-file false --project ./build"
