apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  labels:
    app.kubernetes.io/part-of: konsti
    app.kubernetes.io/component: server
    app.kubernetes.io/name: cron
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: konsti
      app.kubernetes.io/component: server
      app.kubernetes.io/name: cron
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: konsti
        app.kubernetes.io/component: server
        app.kubernetes.io/name: cron
    spec:
      enableServiceLinks: false
      securityContext: !Var konsti_pod_security_context
      containers:
        - name: cron
          image: !Var konsti_image
          env: !Concat
            - !Var konsti_environment
            - - name: ONLY_CRONJOBS
                value: 'true'
          securityContext: !Var konsti_container_security_context
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
              httpHeaders:
                - name: Host
                  value: !Lookup ingress_public_hostnames[0]
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
              httpHeaders:
                - name: Host
                  value: !Lookup ingress_public_hostnames[0]
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts: !Var konsti_volume_mounts
      volumes: !Var konsti_volumes
