apiVersion: apps/v1
kind: Deployment
metadata:
  name: konsti
  labels:
    app.kubernetes.io/part-of: konsti
    app.kubernetes.io/component: server
    app.kubernetes.io/name: konsti
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: konsti
      app.kubernetes.io/component: server
      app.kubernetes.io/name: konsti
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: konsti
        app.kubernetes.io/component: server
        app.kubernetes.io/name: konsti
    spec:
      enableServiceLinks: false
      securityContext: !Var konsti_pod_security_context
      containers:
        - name: konsti
          image: !Var konsti_image
          ports:
            - containerPort: 5000
          env: !Var konsti_environment
          securityContext: !Var konsti_container_security_context
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts: !Var konsti_volume_mounts
      volumes: !Var konsti_volumes
