apiVersion: v1
kind: Secret
metadata:
  name: konsti
  labels:
    app.kubernetes.io/part-of: konsti
type: Opaque
data:
  connString: !Base64,Var mongodb_connection_string
  jwtSecretKey: !Base64,Var konsti_jwt_secret_key
  jwtSecretKeyAdmin: !Base64,Var konsti_jwt_secret_key_admin
  jwtSecretKeyHelp: !Base64,Var konsti_jwt_secret_key_help
  kompassiClientId: !Base64,Var konsti_kompassi_client_id
  kompassiClientSecret: !Base64,Var konsti_kompassi_client_secret
