apiVersion: v1
kind: Service
metadata:
  name: konsti
  labels:
    app.kubernetes.io/part-of: konsti
    app.kubernetes.io/name: konsti
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/part-of: konsti
    app.kubernetes.io/name: konsti
