import { testGame, testGame2 } from "shared/tests/testGame";
import {
  KompassiGameHitpoint,
  KompassiPhysicalPlayHitpoint,
  KompassiProgramTypeHitpoint,
} from "shared/types/models/kompassiGame/kompassiGameHitpoint";

export const testKompassiGameHitpoint: KompassiGameHitpoint = {
  title: testGame.title,
  description: testGame.description,
  category_title: KompassiProgramTypeHitpoint.TABLETOP_RPG,
  formatted_hosts: testGame.people,
  room_name: testGame.location,
  length: testGame.mins,
  start_time: testGame.startTime,
  rpg_system: testGame.gameSystem,
  min_players: testGame.minAttendance,
  max_players: testGame.maxAttendance,
  identifier: testGame.gameId,
  three_word_description: testGame.shortDescription,
  other_author: testGame.otherAuthor,
  physical_play: KompassiPhysicalPlayHitpoint.SOME,
  is_english_ok: false,
  is_age_restricted: false,
  is_beginner_friendly: false,
  is_children_friendly: false,
  is_intended_for_experienced_participants: false,
  is_public: false,
  video_link: "",
};

export const testKompassiGameHitpoint2: KompassiGameHitpoint = {
  title: testGame2.title,
  description: testGame2.description,
  category_title: KompassiProgramTypeHitpoint.TABLETOP_RPG,
  formatted_hosts: testGame2.people,
  room_name: testGame2.location,
  length: testGame2.mins,
  start_time: testGame2.startTime,
  rpg_system: testGame2.gameSystem,
  min_players: testGame2.minAttendance,
  max_players: testGame2.maxAttendance,
  identifier: testGame2.gameId,
  three_word_description: testGame2.shortDescription,
  other_author: testGame2.otherAuthor,
  physical_play: KompassiPhysicalPlayHitpoint.SOME,
  is_english_ok: false,
  is_age_restricted: false,
  is_beginner_friendly: false,
  is_children_friendly: false,
  is_intended_for_experienced_participants: false,
  is_public: false,
  video_link: "",
};
