import { testGame, testGame2 } from "shared/tests/testGame";
import {
  KompassiGame,
  KompassiGameStyle,
  KompassiGenre,
  KompassiProgramType,
  KompassiTag,
} from "shared/typings/models/kompassiGame";

export const testKompassiGame: KompassiGame = {
  title: testGame.title,
  description: testGame.description,
  category_title: KompassiProgramType.TABLETOP_RPG,
  formatted_hosts: testGame.people,
  room_name: testGame.location,
  length: testGame.mins,
  start_time: testGame.startTime,
  end_time: testGame.endTime,
  language: testGame.language,
  rpg_system: testGame.gameSystem,
  min_players: testGame.minAttendance,
  max_players: testGame.maxAttendance,
  identifier: testGame.gameId,
  tags: [KompassiTag.ALOITTELIJAYSTÄVÄLLINEN, KompassiTag.SOPII_ALLE_7V],
  genres: [KompassiGenre.ADVENTURE, KompassiGenre.HUMOR],
  styles: [KompassiGameStyle.CHARACTER_DRIVEN, KompassiGameStyle.RULES_LIGHT],
  short_blurb: testGame.shortDescription,
  revolving_door: false,
  content_warnings: testGame.contentWarnings,
  other_author: testGame.otherAuthor,
  ropecon2018_characters: testGame.maxAttendance,
  ropecon2021_accessibility_loud_sounds: false,
  ropecon2021_accessibility_flashing_lights: false,
  ropecon2021_accessibility_strong_smells: false,
  ropecon2021_accessibility_irritate_skin: false,
  ropecon2021_accessibility_physical_contact: false,
  ropecon2021_accessibility_low_lightning: false,
  ropecon2021_accessibility_moving_around: false,
  ropecon2021_accessibility_video: false,
  ropecon2021_accessibility_recording: false,
  ropecon2021_accessibility_text: false,
  ropecon2021_accessibility_colourblind: false,
  ropecon2022_accessibility_remaining_one_place: false,
  ropecon2022_content_warnings: "Content warning",
  ropecon2021_accessibility_inaccessibility: "Other inaccessibility",
  type_of_game_program: "",
  entry_fee: 0,
};

export const testKompassiGame2: KompassiGame = {
  title: testGame2.title,
  description: testGame2.description,
  category_title: KompassiProgramType.TABLETOP_RPG,
  formatted_hosts: testGame2.people,
  room_name: testGame2.location,
  length: testGame2.mins,
  start_time: testGame2.startTime,
  end_time: testGame2.endTime,
  language: testGame2.language,
  rpg_system: testGame2.gameSystem,
  min_players: testGame2.minAttendance,
  max_players: testGame2.maxAttendance,
  identifier: testGame2.gameId,
  tags: [KompassiTag.ALOITTELIJAYSTÄVÄLLINEN, KompassiTag.SOPII_ALLE_7V],
  genres: [KompassiGenre.ADVENTURE, KompassiGenre.HUMOR],
  styles: [KompassiGameStyle.CHARACTER_DRIVEN, KompassiGameStyle.RULES_LIGHT],
  short_blurb: testGame2.shortDescription,
  revolving_door: false,
  content_warnings: testGame2.contentWarnings,
  other_author: testGame2.otherAuthor,
  ropecon2018_characters: testGame2.maxAttendance,
  ropecon2021_accessibility_loud_sounds: false,
  ropecon2021_accessibility_flashing_lights: false,
  ropecon2021_accessibility_strong_smells: false,
  ropecon2021_accessibility_irritate_skin: false,
  ropecon2021_accessibility_physical_contact: false,
  ropecon2021_accessibility_low_lightning: false,
  ropecon2021_accessibility_moving_around: false,
  ropecon2021_accessibility_video: false,
  ropecon2021_accessibility_recording: false,
  ropecon2021_accessibility_text: false,
  ropecon2021_accessibility_colourblind: false,
  ropecon2022_accessibility_remaining_one_place: false,
  ropecon2022_content_warnings: "Content warning",
  ropecon2021_accessibility_inaccessibility: "Other inaccessibility",
  type_of_game_program: "",
  entry_fee: 0,
};
