import { Game } from 'typings/game.typings';

export const mockGame: Game = {
  gameId: 'p2106',
  title: 'Test game',
  description: 'Test game description',
  location: 'Test location',
  startTime: '2019-07-26T14:00:00.000Z',
  mins: 240,
  tags: [
    'aloittelijaystävällinen',
    'english',
    'lapsiystävällinen',
    'pöytäpelit',
  ],
  genres: ['fantasy', 'war', 'exploration', 'mystery', 'drama'],
  styles: ['serious', 'story_driven', 'character_driven'],
  language: 'fi',
  endTime: '2019-07-26T18:00:00.000Z',
  people: 'Test GM',
  minAttendance: 2,
  maxAttendance: 4,
  gameSystem: 'Test gamesystem',
  englishOk: false,
  childrenFriendly: false,
  ageRestricted: false,
  beginnerFriendly: false,
  intendedForExperiencedParticipants: false,
  shortDescription: 'Short description',
  revolvingDoor: true,
  popularity: 0,
  programType: 'Roolipeli',
};

export const mockGame2: Game = {
  gameId: 'p3001',
  title: 'Test game 2',
  description: 'Test game description',
  location: 'Test location',
  startTime: '2019-07-26T15:00:00.000Z',
  mins: 240,
  tags: [
    'aloittelijaystävällinen',
    'english',
    'lapsiystävällinen',
    'pöytäpelit',
  ],
  genres: ['fantasy', 'war', 'exploration', 'mystery', 'drama'],
  styles: ['serious', 'story_driven', 'character_driven'],
  language: 'fi',
  endTime: '2019-07-26T19:00:00.000Z',
  people: 'Test GM',
  minAttendance: 2,
  maxAttendance: 4,
  gameSystem: 'Test gamesystem',
  englishOk: false,
  childrenFriendly: false,
  ageRestricted: false,
  beginnerFriendly: false,
  intendedForExperiencedParticipants: false,
  shortDescription: 'Short description',
  revolvingDoor: true,
  popularity: 0,
  programType: 'Roolipeli',
};
