version: "3.8"

services:
  server:
    build:
      context: ../.
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - SETTINGS=${APP_SETTINGS}
      - CONN_STRING=mongodb://mongo:27017
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.8-jammy
    container_name: konsti-mongodb
    restart: always
    ports:
      - 27017:27017
