version: "3.8"

services:
  server:
    build:
      context: ../.
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - SETTINGS=CI
      - CONN_STRING=mongodb://mongo:27017
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.6-focal
    restart: always
    ports:
      - 27017:27017
