version: "3.8"

services:
  server:
    network_mode: host
    build:
      context: ../.
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - CONN_STRING=mongodb://localhost:27017
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    network_mode: host
    image: mongo:4.4
    restart: always
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: example
