import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAngleUp as fasAngleUp,
  faAngleDown as fasAngleDown,
  faEye as fasEye,
  faEyeSlash as fasEyeSlash,
  faHeart as fasHeart,
  faBars as fasBars,
  faTimes as fasTimes,
  faComment as fasComment,
  faXmark as fasXmark,
  faCircleQuestion as fasCircleQuestion,
  faQuestion as fasQuestion,
  faInfo as fasInfo,
  faCircleChevronLeft as fasCircleChevronLeft,
  faChevronUp as fasChevronUp,
  faUser as fasUser,
  faUsers as fasUsers,
  faCircle as fasCircle,
  faDice as fasDice,
  faCalendarDays as fasCalendarDays,
  faCalendarXmark as fasCalendarXmark,
  faPersonChalkboard as fasPersonChalkboard,
  faArrowRight as fasArrowRight,
  faDiceThree as fasDiceThree,
  faUserPlus as fasUserPlus,
  faTriangleExclamation as fasTriangleExclamation,
  faCircleExclamation as fasCircleExclamation,
  faCircleCheck as fasCircleCheck,
  faBan as fasBan,
  faCircleArrowRight as fasCircleArrowRight,
  faTicket as fasTicket,
  faFire as fasFire,
  faThermometer0 as fasThermometer0,
  faThermometer1 as fasThermometer1,
  faThermometer2 as fasThermometer2,
  faThermometer3 as fasThermometer3,
  faThermometer4 as fasThermometer4,
} from "@fortawesome/free-solid-svg-icons";
import {
  faHeart as farHeart,
  faComment as farComment,
} from "@fortawesome/free-regular-svg-icons";

export const getIconLibrary = (): void => {
  library.add(
    fasAngleUp,
    fasAngleDown,
    fasEye,
    fasEyeSlash,
    fasHeart,
    farHeart,
    fasBars,
    fasTimes,
    farComment,
    fasComment,
    fasXmark,
    fasCircleQuestion,
    fasQuestion,
    fasInfo,
    fasCircleChevronLeft,
    fasChevronUp,
    fasUser,
    fasUsers,
    fasCircle,
    fasCalendarDays,
    fasDice,
    fasCalendarXmark,
    fasPersonChalkboard,
    fasArrowRight,
    fasDiceThree,
    fasUserPlus,
    fasTriangleExclamation,
    fasCircleExclamation,
    fasCircleCheck,
    fasBan,
    fasCircleArrowRight,
    fasTicket,
    fasFire,
    fasThermometer0,
    fasThermometer1,
    fasThermometer2,
    fasThermometer3,
    fasThermometer4,
  );
};
