import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faComment as farComment,
  faHeart as farHeart,
} from "@fortawesome/free-regular-svg-icons";
import {
  faAngleDown as fasAngleDown,
  faAngleUp as fasAngleUp,
  faArrowRight as fasArrowRight,
  faArrowsRotate as fasArrowsRotate,
  faBan as fasBan,
  faBars as fasBars,
  faBell as fasBell,
  faCalendarDays as fasCalendarDays,
  faCalendarXmark as fasCalendarXmark,
  faChevronDown as fasChevronDown,
  faChevronUp as fasChevronUp,
  faCircle as fasCircle,
  faCircleArrowRight as fasCircleArrowRight,
  faCircleCheck as fasCircleCheck,
  faCircleChevronLeft as fasCircleChevronLeft,
  faCircleExclamation as fasCircleExclamation,
  faCircleQuestion as fasCircleQuestion,
  faComment as fasComment,
  faDice as fasDice,
  faDiceThree as fasDiceThree,
  faEye as fasEye,
  faEyeSlash as fasEyeSlash,
  faFire as fasFire,
  faHeart as fasHeart,
  faInfo as fasInfo,
  faPersonChalkboard as fasPersonChalkboard,
  faQuestion as fasQuestion,
  faThermometer0 as fasThermometer0,
  faThermometer1 as fasThermometer1,
  faThermometer2 as fasThermometer2,
  faThermometer3 as fasThermometer3,
  faThermometer4 as fasThermometer4,
  faTicket as fasTicket,
  faTimes as fasTimes,
  faTriangleExclamation as fasTriangleExclamation,
  faUser as fasUser,
  faUserPlus as fasUserPlus,
  faUsers as fasUsers,
  faXmark as fasXmark,
} from "@fortawesome/free-solid-svg-icons";

export const getIconLibrary = (): void => {
  library.add(
    fasAngleUp,
    fasAngleDown,
    fasEye,
    fasEyeSlash,
    fasHeart,
    farHeart,
    fasBars,
    fasTimes,
    farComment,
    fasComment,
    fasXmark,
    fasCircleQuestion,
    fasQuestion,
    fasInfo,
    fasCircleChevronLeft,
    fasChevronUp,
    fasChevronDown,
    fasUser,
    fasUsers,
    fasCircle,
    fasCalendarDays,
    fasDice,
    fasCalendarXmark,
    fasPersonChalkboard,
    fasArrowRight,
    fasDiceThree,
    fasUserPlus,
    fasTriangleExclamation,
    fasCircleExclamation,
    fasCircleCheck,
    fasBan,
    fasCircleArrowRight,
    fasTicket,
    fasFire,
    fasThermometer0,
    fasThermometer1,
    fasThermometer2,
    fasThermometer3,
    fasThermometer4,
    fasArrowsRotate,
    fasBell,
  );
};
