apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: konsti
  annotations: !Var ingress_annotations
spec:
  ingressClassName: !Var ingress_class_name
  tls: !Var ingress_tls
  rules: !Loop
    over: !Var ingress_public_hostnames
    as: hostname
    template:
      host: !Var hostname
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: konsti
                port:
                  number: 5000
