import {
  InclusivityValue,
  ProgramItem,
  Gamestyle,
  Genre,
  Language,
  ProgramType,
  Tag,
  SignupType,
  Popularity,
  State,
} from "shared/types/models/programItem";

export const testProgramItem: ProgramItem = {
  programItemId: "test-program-item",
  title: "Test program item",
  description: "Test program item description",
  location: "Test location",
  startTime: "2019-07-26T14:00:00.000Z",
  mins: 240,
  tags: [Tag.BEGINNER_FRIENDLY, Tag.SMALL_KIDS],
  genres: [
    Genre.FANTASY,
    Genre.WAR,
    Genre.EXPLORATION,
    Genre.MYSTERY,
    Genre.DRAMA,
  ],
  styles: [
    Gamestyle.SERIOUS,
    Gamestyle.STORY_DRIVEN,
    Gamestyle.CHARACTER_DRIVEN,
  ],
  languages: [Language.FINNISH],
  endTime: "2019-07-26T18:00:00.000Z",
  people: "Test GM",
  minAttendance: 2,
  maxAttendance: 4,
  gameSystem: "Test gamesystem",
  shortDescription: "Short description",
  revolvingDoor: true,
  popularity: Popularity.NULL,
  programType: ProgramType.TABLETOP_RPG,
  contentWarnings: "",
  otherAuthor: "",
  accessibilityValues: [
    InclusivityValue.NO_MOVEMENT,
    InclusivityValue.FLASHING_LIGHTS,
  ],
  otherAccessibilityInformation: "",
  entryFee: "",
  signupType: SignupType.KONSTI,
  state: State.ACCEPTED,
};

export const testProgramItem2: ProgramItem = {
  programItemId: "test-program-item-2",
  title: "Test program item 2",
  description: "Test program item description",
  location: "Test location",
  startTime: "2019-07-26T15:00:00.000Z",
  mins: 240,
  tags: [Tag.BEGINNER_FRIENDLY, Tag.SMALL_KIDS],
  genres: [
    Genre.FANTASY,
    Genre.WAR,
    Genre.EXPLORATION,
    Genre.MYSTERY,
    Genre.DRAMA,
  ],
  styles: [
    Gamestyle.SERIOUS,
    Gamestyle.STORY_DRIVEN,
    Gamestyle.CHARACTER_DRIVEN,
  ],
  languages: [Language.FINNISH],
  endTime: "2019-07-26T19:00:00.000Z",
  people: "Test GM",
  minAttendance: 2,
  maxAttendance: 4,
  gameSystem: "Test gamesystem",
  shortDescription: "Short description",
  revolvingDoor: true,
  popularity: Popularity.NULL,
  programType: ProgramType.TABLETOP_RPG,
  contentWarnings: "",
  otherAuthor: "",
  accessibilityValues: [
    InclusivityValue.NO_MOVEMENT,
    InclusivityValue.FLASHING_LIGHTS,
  ],
  otherAccessibilityInformation: "",
  entryFee: "",
  signupType: SignupType.KONSTI,
  state: State.ACCEPTED,
};
