name: cicd

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

env:
  SKAFFOLD_DEFAULT_REPO: ghcr.io/con2

jobs:
  # TODO DRY
  deploy_staging:
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: pairity/setup-cd-tools@30acb848f9ff747aff4810dac40c5cc0971f485d
        with:
          kubectl: "1.20.4"
          skaffold: "1.20.0"
      - uses: docker/setup-buildx-action@v1
      - run: |
          python3 -m pip install emskaffolden
          emskaffolden -E staging -- run -n konsti-staging

  deploy_production:
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: pairity/setup-cd-tools@30acb848f9ff747aff4810dac40c5cc0971f485d
        with:
          kubectl: "1.20.4"
          skaffold: "1.20.0"
      - uses: docker/setup-buildx-action@v1
      - run: |
          python3 -m pip install emskaffolden
          emskaffolden -E production -- run -n konsti-production
