name: deploy-prod

on:
  workflow_dispatch:

env:
  SKAFFOLD_DEFAULT_REPO: ghcr.io/con2

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: pairity/setup-cd-tools@30acb848f9ff747aff4810dac40c5cc0971f485d
        with:
          kubectl: "1.20.4"
          skaffold: "1.20.0"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - uses: docker/setup-buildx-action@v1
      - run: |
          python3 -m pip install emskaffolden
          emskaffolden -E production -- run -n konsti-production

  sentry-release:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-22.04

    env:
      CI: true
      HUSKY: 0

    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: "yarn"

      - name: Yarn install
        run: |
          yarn --immutable

      - name: Build prod frontend
        run: |
          yarn build-front:prod

      - name: Create prod frontend Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: konsti
          SENTRY_PROJECT: konsti-frontend-prod
        with:
          sourcemaps: "./client/build"
          ignore_missing: true
          ignore_empty: true

      - name: Create prod backend Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: konsti
          SENTRY_PROJECT: konsti-backend-prod
        with:
          ignore_missing: true
          ignore_empty: true
