name: Node CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.1]

    env:
      CI: true

    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: |
          yarn --immutable

      - name: Build front-end
        run: |
          yarn build-front:prod

      - name: Build container
        # if: github.ref == 'refs/heads/master'
        run: |
          yarn docker:build

      - name: Push to AWS ECR
        # if: github.ref == 'refs/heads/master'
        uses: jwalton/gh-ecr-push@v1.3.6
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-1
          image: konsti:latest

  #      - name: Cache build files
  #        uses: actions/cache@v3
  #        with:
  #          path: build-files
  #          key: build-files
