name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.1]

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: |
          yarn --immutable

      - name: Build front-end
        run: |
          yarn build-front:prod

      - name: Run Prettier
        run: |
          yarn prettier:check

      - name: Run ESLint
        run: |
          yarn eslint

      - name: Run stylelint
        run: |
          yarn stylelint

      - name: TS type check
        run: |
          yarn type-check

      - name: Test
        run: |
          yarn test

      - name: Playwright
        run: |
          yarn docker-compose:test
