name: Node CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.1]

    env:
      CI: true

    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: |
          yarn --immutable

      - name: Build front-end
        run: |
          yarn build-front:prod

  deploy:
    needs: [build]
    # if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - name: Build container
        run: |
          yarn docker:build

      - name: Push to Amazon ECR
        uses: jwalton/gh-ecr-push@v1.3.6
        with:
          region: eu-west-1
          image: konsti:latest
