name: sentry-release

on:
  push:
    branches:
      - development
      - main

jobs:
  staging:
    if: github.ref == 'refs/heads/development'

    runs-on: ubuntu-22.04

    env:
      CI: true

    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "yarn"

      - name: Yarn install
        run: |
          yarn --immutable

      - name: Build staging frontend
        run: |
          yarn build-front:staging

      - name: Create staging frontend Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: konsti
          SENTRY_PROJECT: konsti-frontend-staging
        with:
          sourcemaps: "./client/build"
          ignore_missing: true
          ignore_empty: true

      - name: Create staging backend Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: konsti
          SENTRY_PROJECT: konsti-backend-staging
        with:
          ignore_missing: true
          ignore_empty: true

  production:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-22.04

    env:
      CI: true

    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "yarn"

      - name: Yarn install
        run: |
          yarn --immutable

      - name: Build prod frontend
        run: |
          yarn build-front:prod

      - name: Create prod frontend Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: konsti
          SENTRY_PROJECT: konsti-frontend-prod
        with:
          sourcemaps: "./client/build"
          ignore_missing: true
          ignore_empty: true

      - name: Create prod backend Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: konsti
          SENTRY_PROJECT: konsti-backend-prod
        with:
          ignore_missing: true
          ignore_empty: true
